### PR TITLE
feature: queue throttling

### LINKED ISSUE #3: Allow message throttle settings
> In the same way as deferring messages is possible, allow messages to be throttled, that is, run x times per specified duration.

Original issue: https://github.com/dadi/queue-wrapper/issues/1
Cited example: https://www.npmjs.com/package/job-broker

### PR DESCRIPTION
**Pull request by adamkdean**
BREAKING CHANGE: config format changed for throttling, replace your `{ throttle: 5 }` with `{ throttle: { workers: 5 } }`

Closes #3.

Queue throttling introduces the ability to control how many messages are processed in a defined timespan. This can be useful if a consumer (worker) uses external APIs which are rate limited, for example.

This also introduces a breaking change, in that the previous configuration for throttling the number of concurrent workers has been abstracted from `broker.throttle` to `broker.throttle.workers`.

* ability to set a default rate limit for the queue
* ability to set message specific rate limits

See the README for updated configuration documentation.

Here is an example:

```
"throttle": {
  "workers": 5,
  "queue": {
    "unit": "second",
    "value": 1
  },
  "messages": [
    {
      "name": "ten-per-second",
      "regex": "^tps-.*$",
      "regexOpts": "i",
      "unit": "second",
      "value": 10
    },
    {
      "name": "one-per-minute",
      "regex": "^opm-.*$",
      "regexOpts": "i",
      "unit": "minute",
      "value": 1,
      "discard": true
    }
  ]
}
```

### CODE REVIEW

**Comment by jimlambie** [comment]
@adamkdean  is this finished?

**Comment by adamkdean** [comment]
Sorry @jimlambie, not yet, will remove the in progress labels and assign to you when ready

**Comment by adamkdean** [comment]
@jimlambie 🏀

**Comment by adamkdean** [comment]
Going to add more `features`. Please hold. `IN PROGRESS`. 🚧

**Comment by adamkdean** [comment]
`features` @jimlambie ✅ 🏀

**Comment by jimlambie** [comment]
@adamkdean this looks great - ok to merge?

**Review by jimlambie — APPROVED** [review]

**Comment by adamkdean** [comment]
@jimlambie it should be okay to merge, yep. Are you happy to do it?

**Pull request merged**
